apiVersion: v1
kind: Secret
metadata:
    name: pactbroker-access
    labels:
        app: {{ include "pact-broker.name" . }}
type: Opaque
stringData:
    url: {{ printf "\"http://%s\"" (index .Values.ingress.hosts "0").host }}
