apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id
  name: "another-test-usernamepass"
  labels:
    # so we know what type it is
    # available types: certificate, secretFile, secretText, usernamePassword, basicSSHUserPrivateKey
    # https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/examples/
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    # description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: myUsername
  password: 'Pa$$word'
