apiVersion: v1
kind: Secret
metadata:
  name: artifactory-access
  labels:
    "app.kubernetes.io/name": 'artifactory'
    "app.kubernetes.io/instance": "artifactory"
type: Opaque
stringData:
  password: {{ .Values.username }}
  username: {{ .Values.password }}
  url: {{ .Values.url }}
