commonLabels:
 app: "jenkins"
resources:
 - ibmcloud_apikey.yaml
 - jenkins.yaml
 - jenkins_config.yaml
patchesJson6902:
 - path: patch-role.yaml
   target:
     group: rbac.authorization.k8s.io
     version: v1
     kind: Role
     name: jenkins-schedule-agents
     namespace: tools
#
# - path: patch-test.yaml
#   target:
#     group: ""
#     version: v1
#     kind: Pod
#     name: jenkins-ui-test-f7vdc

