image:
  pullPolicy: Always

ingress:
  enabled: true
  # Used to create an Ingress record.
#  hosts:
#    - name: sonar.organization.com

persistence:
  enabled: true
  storageClass: "ibmc-file-gold"
  accessMode: ReadWriteOnce
  size: 2Gi

postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: false
#  postgresUser: "sonarUser"
#  postgresPassword: "sonarPass"
#  postgresDatabase: "sonarDB"
#  postgresServer: ""
#  service:
#    port: 5432
